#!/bin/bash
# start saved screen sessions at system start
# Simon Walz, 2018

# add to crontab via:
#	crontab -e
# add:
#	@reboot	/full/path/to/screen-auto-start

# default dir where to save the screen sessions:
DEFAULT_SAVE_DIR="${SCREEN_SAVE_DIR:-"${HOME}/.screenrc-"}"
SAVE_DIR="${DEFAULT_SAVE_DIR}"

if test "x$1" = "x--help" || test "x$1" = "x-h"
then
	echo "usage: prog [savedir]" >&2
	echo "	savedir	- load configs from directory" >&2
	exit 2
fi

if test "x$1" != "x"
then
	SAVE_DIR="$1"
fi
if test -d "${SAVE_DIR}"
then
	SAVE_DIR="${SAVE_DIR}/"
fi


for file in "${SAVE_DIR}"*
do
	echo /usr/bin/env screen -d -m -c "$file"
done
