#!/bin/bash
# save all my screen sessions
# Simon Walz, 2018

SCRIPTPATH="$(readlink -f 2>/dev/null || perl -MCwd -e 'print Cwd::abs_path shift' "$0")"
SCRIPTDIR="$(dirname "${SCRIPTPATH}")"

set -e
shopt -s nullglob

savedir="$1"

if test "$1" = "--help" || test "$1" = "-h"
then
	echo "usage: prog [-d|savedir]" >&2
	echo "  -d      - use .screen-save/YYYY-MM-DD/ aus save dir" >&2
	echo "	savedir	- save to directory" >&2
	exit 2
fi

screen_sockets=(/var/run/screen/S-*/*);

for screen_info in "${screen_sockets[@]#*S-}";
do
	screen_user=$(dirname "${screen_info}")
	screen_pid=$(basename "${screen_info%.pts*}")
	command=""

	if test "$1" = "-d"
	then
		savedir="~${screen_user}/.screen-save/$(date +%Y-%m-%d)/"
		command="mkdir -p ${savedir}"
		if [ "$EUID" -ne 0 ]; then
			eval "${command}"
		else
			su - "${screen_user}" -c "${command}"
		fi
	fi
	command="${SCRIPTDIR}/screen-save ${screen_pid} ${savedir} </dev/null"
	if [ "$EUID" -ne 0 ]; then
		eval "${command}"
	else
		su - "${screen_user}" -c "${command}"
	fi
done

