#!/bin/sh
# save all my screen sessions
# Simon Walz, 2018

SCREEN_PID=`screen -ls | \
	grep -oE "^\s+[0-9]+\." | \
	grep -oE "[0-9]+"`

for i in ${SCREEN_PID}
do
	screen-save "${i}" </dev/null
done

