#!/bin/bash
# save screen sessions to screenrc compatible files
# Simon Walz, 2018

# configuration:
# processes with shall be stated automatically:
ALLOWED_PROCESSES="^vim |^top|^htop|^watch |^ping "

# default dir where to save the screen sessions:
DEFAULT_SAVE_DIR="${SCREEN_SAVE_DIR:-"${HOME}/.screenrc-"}"

debug() {
	# remove "#" to enable debug output:
	#echo "$@" >&2
	return
}


# script:
C=""
write() {
	if test "$1" = "-n"; then
		shift;
		C="${C}$@"
		return
	fi
	C="${C}$@
"
}

doublequote() {
	local output
	for i in "$@"
	do
		i=${i//\\/\\\\}
		i='"'${i//\"/\\\"}'"'
		echo -n "$i"
	done
	echo
}

singlequote() {
	for i in "$@"
	do
		i=\'${i//\'/\'\\\'\'}\'
		echo -n "$i"
	done
	echo
}

escape_screen_config() {
	doublequote "$@"
}

escape_shell() {
	singlequote "$@"
	#for i in "$@"
	#do
	#	echo -n "${i@Q}"
	#done
	#echo
}

read_cmdline() {
	local window_pid
	window_pid="$1"
	local format
	format="%s"
	( while IFS= read -r -d $'\0' ARG
	do
		if test "$(echo "${ARG}" | tr -d 'A-Za-z0-9.=_-')" = ""
		then
			printf "${format}" "${ARG}"
		else
			printf "${format}" "$(escape_shell "${ARG}")"
		fi
		format=" %s"
	done ) <"/proc/${window_pid}/cmdline"
}

# check parameters:
SCREEN_SEARCH="$1"
SAVE_FILE="$2"

if test "${TESTCASES}" = "screen-save"
then
	return
fi

if test "${SCREEN_SEARCH}" = "" || test "${SCREEN_SEARCH}" = "--help";
then
	echo "usage: prog [-t] screenname [savefile]" >&2
	echo "	[-t]		- use this screen session (optional)" >&2
	echo "	screenname	- use session with name" >&2
	echo "	savefile	- save to file" >&2
	echo "			  default: ~/.screenrc-SESSIONNAME" >&2
	exit 2
fi
if test "${SCREEN_SEARCH}" = "-t";
then
	if test "${STY}" = "";
	then
		echo "No screen name given by STY var" >&2
		echo "" >&2
		echo "Not inside of a screen session?" >&2
		exit 1
	fi
	# session name in sty is not updated.
	SCREEN_PID="$(echo ${STY} | grep -oE "^\s*[0-9]+" | grep -oE "[0-9]+")"
	C_SCREEN_NAME="$2"
	SAVE_FILE="$3"
else
	# search for sessionname, pid or full id
	# parse screen list:
	SCREEN_PID=$(screen -S "${SCREEN_SEARCH}" -ls | \
		grep -E "\.${SCREEN_SEARCH}\s|^\s+${SCREEN_SEARCH}(\.|\s)" | \
		grep -oE "^\s+[0-9]+\." | \
		grep -oE "[0-9]+")
fi

if test "${SCREEN_PID}" = ""
then
	echo "Process not found." >&2
	exit 1
fi

# get sessionname from screen:
SCREEN_NAME="$(screen -S ${SCREEN_PID} -Q echo '${STY}')"

# screen id is pid + name:
SCREEN_ID="${SCREEN_PID}.${SCREEN_NAME}"

# if pts or tty: there is no sessionname:
echo "${SCREEN_NAME}" | grep -E "^pts" >/dev/null
if test "$?" = "0"; then
	SCREEN_NAME=""
fi
echo "${SCREEN_NAME}" | grep -E "^tty" >/dev/null
if test "$?" = "0"; then
	SCREEN_NAME=""
fi

# set user sessionname:
if test "${C_SCREEN_NAME}" != ""; then
	SCREEN_NAME="${C_SCREEN_NAME}"
fi
if test "${SCREEN_NAME}" = ""; then
	read -p "The screen session does not have a name. Please set one: " SCREEN_NAME
fi
if test "${SCREEN_NAME}" = ""; then
	SCREEN_NAME="pid-${SCREEN_SEARCH}"
fi

# get screens cwd:
SCREEN_CWD="$(screen -S "${SCREEN_ID}" -Q echo '${PWD}')"

write "# from .screenrc (filtered):"
write "$(grep -Ei "^(def|source|colon|setenv|unsetenv|shell|shelltitle|term|password|lockscreen|multiuser|acladd|addacl|aclchg|chacl|acldel|aclgrp|aclumask|umask|wall|resize|caption|fit|mousetrack|width|height|utf8|scrollback|bind|unbindall|escape|meta|dump|echo|sleep|log|startup_message|debug|crlf|caption)" "${HOME}/.screenrc" 2>/dev/null)"
#write "source \"${HOME}/.screenrc\""
write
write "# saved session:"
write "sessionname \"${SCREEN_NAME}\""
write

debug SCREENNAME=${SCREEN_NAME}
debug SCREEN_ID=${SCREEN_ID}
debug "path: ${SCREEN_CWD}"
debug


# create directory for window contents:
mkdir -p "${HOME}/.screen_hardcopy"

# for all windows:
for WINDOW_PID in $(ps -o pid= --ppid "${SCREEN_PID}")
do
	# get window id:
	# LIMITATION: Changing the number of a window is not supported.
	# The window number is read from the environment, which can not
	# be updated by screen.
	WINDOW_ID="$(xargs --null --max-args=1 echo \
		</proc/${WINDOW_PID}/environ | grep -w WINDOW | grep -oE "[0-9]+")"

	# read cmdline:
	WINDOW_CL="$(read_cmdline "${WINDOW_PID}")"


	# get cwd of window:
	WINDOW_CWD="$(readlink /proc/${WINDOW_PID}/cwd)"
	
	# get title of window:
	WINDOW_TITLE="$(screen -S "${SCREEN_ID}" -p "${WINDOW_ID}" -Q title)"

	# ask screen for window contents:
	screen -S "${SCREEN_ID}" -p "${WINDOW_ID}" -X hardcopy "${HOME}/.screen_hardcopy/${SCREEN_NAME}_${WINDOW_ID}"
	# screen -h = full history

	# wait till file is writen:
	sleep 0.01
	if test \! -f "${HOME}/.screen_hardcopy/${SCREEN_NAME}_${WINDOW_ID}"
	then
		echo "Fehler: hardcopy not found." >&2
		exit 2
	fi

	# get window contents, alter it, zip it, encode it with base64:
	WINDOW_CONTENTS="$(awk '/^$/{next}NR>1 {print last} {last=$0}' \
		"${HOME}/.screen_hardcopy/${SCREEN_NAME}_${WINDOW_ID}" | \
		gzip -c -9 | base64 -w 0 | sed ':a;N;$!ba;s/\n/\\n/g')"
	rm "${HOME}/.screen_hardcopy/${SCREEN_NAME}_${WINDOW_ID}"

	debug "[${WINDOW_ID}] ${WINDOW_TITLE} - ${WINDOW_CL}"
	debug "${WINDOW_CWD}"

	PROCESS_CL=""
	for PROCESS_PID in $(ps -o pid= --ppid "${WINDOW_PID}")
	do
		debug "PID=${PROCESS_PID}"

		# get command file:
		PROCESS_CL="$(read_cmdline "${PROCESS_PID}")"

		# get cwd of process:
		#PROCESS_CWD="$(readlink /proc/${PROCESS_PID}/cwd)"

		debug "\> ${PROCESS_CL}"

		# if process is a allow process, do exec command:
		echo "${PROCESS_CL}" | grep -E "${ALLOWED_PROCESSES}" \
				>/dev/null 2>&1
		if test "$?" = "0"
		then
			PROCESS_CL="${PROCESS_CL}\\n"
		fi
	done

	# create window:
	write "chdir \"${WINDOW_CWD}\""
	write "screen -t \"${WINDOW_TITLE}\" ${WINDOW_ID} ${WINDOW_CL}"

	# add window contents and command:
	if test "${PROCESS_CL}" != "" || test "${WINDOW_CONTENTS}" != ""
	then
		EXEC_CL="sleep 0.2;echo '${WINDOW_CONTENTS}'|base64 -d|gzip -cd"
		if test "${PROCESS_CL}" != ""
		then
			EXEC_CL="${EXEC_CL};echo -n $(escape_shell "${PROCESS_CL}") >&2"
		fi
		write -n "at \"${WINDOW_ID}#\" exec !.! sh -c "
		write "$(escape_screen_config "${EXEC_CL}")"
	fi
	# alternative code
	# screen -S dokuweb -p 0 -X stuff "ls\n"
#	if test "${PROCESS_CL}" != ""; then
#		write "at \"${WINDOW_ID}#\" stuff \"${PROCESS_CL}\""
#	fi

	# add newlines
	write
	debug

done

write
write "# bug in screen: changing cwd of screen breaks term cap:"
write "chdir \"${SCREEN_CWD}\""
write "chdir"
write
write "# bug in screen: last write command not executed"
write "screen '/bin/false'"
write
write "# vim: ft=screen"

# clean status line:
screen -S "${SCREEN_ID}" -Q echo ''


# save session file:
if test "${SAVE_FILE}" = ""; then
	SAVE_FILE="${DEFAULT_SAVE_DIR}${SCREEN_NAME}"
fi
if test -d "${SAVE_FILE}"; then
	SAVE_FILE="${SAVE_FILE}/${SCREEN_NAME}"
fi
if test "${SAVE_FILE}" = "-"; then
	echo "${C}"
else
	mkdir -p "$(dirname "${SAVE_FILE}")"
	echo "${C}" >"${SAVE_FILE}"
fi

