#!/bin/sh
# start saved screen sessions at system start
# Simon Walz, 2018

# add to crontab via:
#	crontab -e
# add:
#	@reboot	/full/path/to/screen-auto-start

# default dir where to save the screen sessions:
DEFAULT_SAVE_DIR="${HOME}/.screenrc-"


for file in "${DEFAULT_SAVE_DIR}"*
do
	/usr/bin/env screen -d -m -c "$file"
done
