#!/bin/sh
# save all my screen sessions
# Simon Walz, 2018

SCREEN_PID=`screen -ls | \
	grep -E "\.${SCREEN_NAME}\s" | grep -oE "^\s+[0-9]+\." | \
	grep -oE "[0-9]+"`


for i in "${SCREEN_PID}"
do
	echo screen-save "${i}" </dev/null
done

