name: release

on:
  push:
    branch:
      - 'issue_10_debian_packaging'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create DEB package
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=binary --no-sign
      - name: Upload DEB package
        uses: actions/upload-artifact@v4
        with:
          path: debian/artifacts/
          name: debian_package
      - name: Remove debuginfo file
        run: |
          rm *-debuginfo-*.rpm || true
      - name: Release package files
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          files: |
            ./*.deb
            ./*.rpm
          generate_release_notes: true
